---
title: "Teaching"
output: html_document
---

<br>

#### Comparative Politics, Chinese Politics, and Political History

1. Instructor, PS 324 Political Power in Contemporary China, planned in Spring 2023 ([sample syllabus](sample_syllabus.pdf))

2. TA, PS 400 Chinese Politics, Fall 2020

3. TA, PS 120 Politics Around the World, Fall 2018; Spring 2019; Fall 2019

4. TA, ASIA 378 War Crimes and Memory in East Asia (at Macalester College), Spring 2013

<br>

#### Economics, Game Theory, and Data Analytics

1. TA, PS 348 Analysis of International Relations, Fall 2021, Fall 2022

2. TA, PS 270 Understanding Political Numbers, Spring 2020, 2021

3. TA, PPOL 649 Macroeconomics (at Georgetown), Spring 2017

<br>

#### Chinese-Language Course in Political Economy

In the summer of 2018, I taught at Beijing's [Veritas Academy](https://www.veritaschina.org), where I introduced basic concepts of political economy to an outstanding group of Chinese high schoolers and undergrads. Later, I developed a short, Chinese-language textbook from my lecture notes used for the course, aiming at Chinese college students who want to develop a preliminary knowledge of modern political economy.

I have made all lecture notes available for download. Please feel free to use or distribute it with proper attribution.

1. [Chapter One: Utility Theory; Demand and Supply; Price Theory](teaching_files/va1.pdf)


2. [Chapter Two: Theory of the Market](teaching_files/va2.pdf)


3. [Chapter Three: Corrections to Market Failure; Distribution of Public Goods; Coase Theorem](teaching_files/va3.pdf)


4. [Chapter Four: The Principle-Agent Problem; Theory of Bureacracy and Delegation](teaching_files/va4.pdf)


5. [Chapter Five: Public Choice Theories: Buchanan, Tullock, and Ostrom](teaching_files/va5.pdf)


6. [Chapter Six: Theories of State-building and Social Revolutions](teaching_files/va6.pdf)


7. [Chapter Seven: Theories of Revolution, Democratization and Democratic Consolidation](teaching_files/va7.pdf)